@validationEndErrorMsg = (type) ->
  switch type
    when 'required' then 'est requis.'
    when 'minString' then 'n\'est pas assez long(ue).'
    when 'maxString' then 'est trop long(ue).'
    when 'minNumber' then 'est trop petit(e).'
    when 'maxNumber' then 'est trop grand(d).'
    when 'minDate' then 'est trop ancien(ne).'
    when 'maxDate' then 'est trop récent(e).'
    when 'badDate' then 'est dans un mauvais format de date.'
    when 'minCount' then 'n\'a pas assez de valeurs.'
    when 'maxCount' then 'a trop de valeurs.'
    when 'noDecimal' then 'doit être entier(e).'
    when 'notAllowed' then 'n\'est pas autorisé(e).'
    when 'expectedString' then 'doit être une chaîne de caractères.'
    when 'expectedNumber' then 'doit être un nombre.'
    when 'expectedBoolean' then 'doit être un booléen.'
    when 'expectedArray' then 'doit être un tableau.'
    when 'expectedObject' then 'est mal formaté(e).'
    when 'expectedConstructor' then 'est mal formaté(e).'
    when 'regEx' then 'est mal formaté(e).'
